### ISSUE TITLE
运行后，app.js占6m，怎么破？

### ISSUE THREAD

**Issue by sweetLeo** [ShareQiu1994/cesium-vue#1]
app.js把cesium放进去了，怎么抽离拆分，在运行后没那么大？

**Comment by ShareQiu1994** [comment]
vuecli开发环境中 运行的模块都会包含于app.js中  编译后的生产环境不会这么大 . 
另外2018/5/19做了一次更新 
默认情况下，编译后的Webpack将Cesium 与我们的应用程序放在同一个块中，结果是巨大的。 此次更新将Cesium拆分成独立的代码块。
