### ISSUE TITLE
yarn serve 报错

### ISSUE THREAD

**Issue by skylark36** [ShareQiu1994/cesium-vue#12]

**Comment by skylark36** [comment]
![image](https://user-images.githubusercontent.com/19505695/149301311-ab0dc39b-9e3d-490d-b86d-d642401045a9.png)

**Comment by skylark36** [comment]
在`vue.config.js`里加上这段解决了

```js
          {
            test: /\.js$/,
            include: path.resolve(__dirname, 'node_modules/cesium/Source'),
            use: {
              loader: '@open-wc/webpack-import-meta-loader'
            }
          }
```

**Comment by ShareQiu1994** [comment]
感谢反馈~

这个问题是在 1.84+版本在 ./node_modules/cesium/Source/ThirdParty/zip.js 文件中使用了 import.meta 语法，webpack 默认不支持，在进行项目构建时，会报以上错误，提示信息需要添加 loader。

目前临时解决的办法是安装  @open-wc/webpack-import-meta-loader  模块
vue.config.js 添加 
```
rules: [{
        test: /\.js$/,
        use: {
          loader: '@open-wc/webpack-import-meta-loader',
        },
      }]
```

但是该方法会导致npm run build时不通过，目前没有更好的解决方案，我已将cesium默认版本设置为1.84~ 后续会观察官方的更新

**Comment by skylark36** [comment]
![image](https://user-images.githubusercontent.com/19505695/149476907-b32cc9c6-b186-40d9-810c-954424f64626.png)
感谢回复，在vue.config.js里添加这行可以解决build的问题

**Comment by ShareQiu1994** [comment]
> ![image](https://user-images.githubusercontent.com/19505695/149476907-b32cc9c6-b186-40d9-810c-954424f64626.png) 感谢回复，在vue.config.js里添加这行可以解决build的问题

再次感谢，你的方法在 yarn 安装的环境下完美生效， 在 cnpm 安装的模块中编译尚有问题，因此后续会建议用yarn安装 

该问题可以关闭了
