### ISSUE TITLE
你好，大神，怎么把cesium-navigation这个组件嵌入到框架中？

### ISSUE THREAD

**Issue by shengxuanlin** [ShareQiu1994/cesium-vue#3]
你好，大神，怎么把cesium-navigation这个组件嵌入到框架中，需要做什么设置，我现在使用这个https://github.com/nmccready/cesium-navigation包，但是直接引入后会报错。
![image](https://user-images.githubusercontent.com/29223248/50141733-34e89400-02e3-11e9-9be4-4efc6ebfc774.png)

**Comment by ShareQiu1994** [comment]
cesium-navigation官方没npm包 推介使用https://github.com/ShareQiu1994/cesium-vue-static 静态版本

**Comment by ShareQiu1994** [comment]
最近发现了一个导航插件Npm的包 可以兼容使用 https://github.com/richard1015/cesium-navigation-es6

**Comment by richard1015** [comment]
谢谢老板推荐https://github.com/richard1015/cesium-navigation-es6 @ShareQiu1994 
@shengxuanlin
