### ISSUE TITLE
SuperMap iClient3D for WebGL替换Cesium

### ISSUE THREAD

**Issue by damacha-z** [ShareQiu1994/cesium-vue#5]
您好，我下载了您的程序包，我想要把原生的Cesium代码替换成 SuperMap iClient3D for WebGL（因为超图在Cesium的基础上进行了再封装，支持SuperMap iServer发布的图层服务），请问这样做可以吗？

**Comment by ShareQiu1994** [comment]
可以的，在public目中html引入SuperMap iClient3D for WebGL.js  当做全局变量使用
