### ISSUE TITLE
npm run serve时候，出现无cesium，请大神指点！

### ISSUE THREAD

**Issue by loooon** [ShareQiu1994/cesium-vue#7]
ERROR  Failed to compile with 1 errors                               2:47:18 PM

This dependency was not found:

* Cesium in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/CesiumContainer.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save Cesium

**Comment by wanghongrui** [comment]
`import { Viewer } from 'Cesium'`

改成

`import { Viewer } from 'cesium'`

**Comment by novgis** [comment]
如果是引用本地修改的 Cesium 而不是 npm 安装的版本，怎么处理，请大神指点

**Comment by ShareQiu1994** [comment]
> 如果是引用本地修改的 Cesium 不是 npm 安装的版本，怎么处理，请大神指点

可以使用public目中html文件中引入Cesium.js  Cesium当做一个全局变量
